language: ruby
services:
  - redis-server
rvm:
  - 1.9.3
  - jruby-19mode
  - 2.0.0
  - 2.1.0
  - 2.1.1
env:
  matrix:
    - SIDEKIQ_VERSION="~> 2.14.0"
    - SIDEKIQ_VERSION="~> 2.17.0"
    - SIDEKIQ_VERSION="~> 3.0.0"
